export default {
  Main: "Main",
  Login: "Login",
  Register: "Register",
  Home: "Home",
  Download: "Download",
  Search: "Search",
  CourseDetail: "CourseDetail",
  ListCourses: "ListCourses",
  ListPath: "ListPath",
  Profile: "Profile",
  Loading: "Loading",
  ForgotPass: "ForgotPass",
  Browse: "Browse",
};
